#pragma config(Sensor, in1,    ArmPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  option1,        sensorDigitalIn)
#pragma config(Sensor, dgtl2,  option2,        sensorDigitalIn)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LeftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightRear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Arm,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void stopDrive()
{
	motor[LeftFront]=0;
	motor[LeftRear]=0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void fwd(int t)
{
	motor[LeftFront]=127;
	motor[LeftRear]=127;
	motor[RightFront]=127;
	motor[RightRear]=127;
	wait1Msec(t);
	motor[LeftFront]=-0;
	motor[LeftRear]=-0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void fwdp()
{
	motor[LeftFront]=127;
	motor[LeftRear]=127;
	motor[RightFront]=127;
	motor[RightRear]=127;
}
void bwd(int t)
{
	motor[LeftFront]=-127;
	motor[LeftRear]=-127;
	motor[RightFront]=-127;
	motor[RightRear]=-127;
	wait1Msec(t);
	motor[LeftFront]=-0;
	motor[LeftRear]=-0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void slightRight(int t, int d)
{
	motor[RightFront]=127 - d;
	motor[LeftFront]=127;
	motor[LeftRear]=127;
	motor[RightRear]=127;
	wait1Msec(t);
	motor[LeftFront]=-0;
	motor[LeftRear]=-0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}
void Right(int t)
{
	motor[LeftFront]=127;
	motor[LeftRear]=127;
	motor[RightFront]=-127;
	motor[RightRear]=-127;
	wait1Msec(t);
	motor[LeftFront]=-0;
	motor[LeftRear]=-0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void Left(int t)
{
	motor[LeftFront]=-127;
	motor[LeftRear]=-127;
	motor[RightFront]=127;
	motor[RightRear]=127;
	wait1Msec(t);
	motor[LeftFront]=-0;
	motor[LeftRear]=-0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void PowerLeft(int t)
{
	motor[LeftFront]=127;
	motor[LeftRear]=127;
	wait1Msec(t);
	motor[LeftFront]=0;
	motor[LeftRear]=0;
}

void PowerRight(int t)
{
	motor[RightFront]=127;
	motor[RightRear]=127;
	wait1Msec(t);
	motor[RightFront]=0;
	motor[RightRear]=0;
}

void powerleftadjust()
{
	motor[LeftFront]=127;
	motor[LeftRear]=127;
}

void powerrightadjust()
{
	motor[RightFront]=127;
	motor[RightRear]=127;
}

void powerleftadjustuntil(float n)
{

	motor[LeftFront]=127;
	motor[LeftRear]=127;
}

void powerrighttadjustuntil()
{
	motor[RightFront]=127;
	motor[RightRear]=127;
}

void ArmUpStart()
{

	motor[Arm]=127;
}

void ArmDownStart()
{

	motor[Arm]=-127;
}

void ArmStop()
{

	motor[Arm]=0;
}

void bwdSlow(int t)
{
	motor[LeftFront]=-85;
	motor[LeftRear]=-85;
	motor[RightFront]=-85;
	motor[RightRear]=-85;
	wait1Msec(t);
	motor[LeftFront]=0;
	motor[LeftRear]=0;
	motor[RightFront]=0;
	motor[RightRear]=0;
}
int ArmAngle;


void ArmAngleUp (int a)
{

	motor[Arm]=127;
	while (SensorValue[ArmPot]<a)
	{
	}

	motor[Arm]=0;

}

void ArmAngleDown (int a)
{

	motor[Arm]=-127;
	while (SensorValue[ArmPot]>a)
	{
	}

	motor[Arm]=0;

}



void MiddleFlag()
{
	bwd(6000);
}
void RightAuton()
{
	fwd(2100);
	Right(750);
	bwd(2000);

}

void LeftAuton()
{
	fwd(2100);
	Left(750);
	bwd(2000);
}


task autonomous()
{
	if (SensorValue[option1]>0){
		if (SensorValue[option2]>0){
			RightAuton();// nothing
		}
		else{
			LeftAuton();// jumper in only 2
		}
	}
	else{
		MiddleFlag();// jumper in port 1 or, both 1 and 2
	}
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		motor[LeftFront]=vexRT[Ch3];
		motor[LeftRear]=vexRT[Ch3];
		motor[RightFront]=vexRT[Ch2];
		motor[RightRear]=vexRT[Ch2];

		if(vexRT[Btn5U]==1)
		{

			motor[Arm]=127;
		}
		else
		{
			if(vexRT[Btn5D]==1)
			{

				motor[Arm]=-127;
			}
			else
			{

				motor[Arm]=12;
			}
		if(vexRT[Btn6U]==1)
		{
			motor[Intake]=127;
		}
		else
		{
			if(vexRT[Btn6D]==1)
			{

				motor[Intake]=-127;
			}
			else
			{

				motor[Intake]=0;
			}
		}

		}

}}
